name: Eric Kerkhoven
favicon: null
layout_spectrum: 0.13138
typography_spectrum: 0.47963
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010207'
    - '#f9f4d6'
    - '#b5b382'
    - '#515437'
    - '#787650'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0
purpose: []
