name: Eric Kerkhoven
favicon: null
layout_spectrum: 0.42759
typography_spectrum: 0.04495
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010207'
    - '#f9f4d6'
    - '#b5b382'
    - '#515437'
    - '#787650'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
