name: Eric Kerkhoven
favicon: null
layout_spectrum: 0.12833
typography_spectrum: 0.48492
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#121013'
    - '#6e605f'
    - '#3a3038'
    - '#b8b596'
    - '#b09252'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0
purpose: []
