name: Eric Kerkhoven
favicon: null
layout_spectrum: 0.5202960406895727
typography_spectrum: 0.5716886213049293
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5595290290657431
  lightness: 0.351250980515033
  saturation: 0.4022771955933422
  rhythmicContrast: 0.7311597834341228
purpose: []
